### ISSUE TITLE
isInUseContext 

### ISSUE THREAD

**Issue by jgladen** [mhevery/qwik-i18n#1]
```yarn build.client``` reports:

```
error during build:
Error: 'isInUseContext' is not exported by node_modules/@builder.io/qwik/core.min.mjs, imported by src/i18n.js
```

**Comment by AlanLes** [comment]
Hello, I've got a different one. I've tried to reproduce your error and I've stuck on the same step `yarn build.client` but with different output:
```bash
yarn i18n-extract
yarn run v1.22.19
$ vite build
vite v3.1.1 building for production...
✓ 51 modules transformed.
'useLang' is not exported by node_modules/@builder.io/qwik/core.min.mjs, imported by src/i18n.js
file: /usr/justfun/qwik-i18n/src/i18n.js:4:21
2: import "@angular/localize/init";
3: import { loadTranslations } from "@angular/localize";
4: import { useEnvData, useLang, withLang, useOnDocument } from "@builder.io/qwik";
                        ^
5: import EN from "./locale/message.en.json";
6: import SK from "./locale/message.sk.json";
error during build:
Error: 'useLang' is not exported by node_modules/@builder.io/qwik/core.min.mjs, imported by src/i18n.js
    at error (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at TrackingScope.findVariable (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at BlockScope.findVariable (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at FunctionScope.findVariable (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///usr/justfun/qwik-i18n/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node_modules/.bin/localize-extract -s "dist/build/*.js" -f json -o src/locale/message.en.json
✨  Done in 1.04s.
```

**Comment by jgladen** [comment]
I to am getting the same error now. since [fixes for qwik-city](https://github.com/mhevery/qwik-i18n/commit/f31a92ae83507617ef5f81caca6ccbb54b3f5de3) . Maybe it's a development version of @builder.io/qwik ?
